assistant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='journal/')), 
    path('journal/', include('journal.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('expenses/', include('expenses.urls')),
]

expenses/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', ExpenseList.as_view(), name='expense_list'), 
    path('create/', ExpenseCreate.as_view(), name='expense_create'), 
    path('<int:pk>/update/', ExpenseUpdate.as_view(), name='expense_update'), 
    path('<int:pk>/delete/', ExpenseDelete.as_view(), name='expense_delete'),
]

journal/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', JournalList.as_view(), name="journal_list"), 
    path('create/', JournalCreate.as_view()),
    path('<int:pk>/update/', JournalUpdate.as_view()), 
    path('<int:pk>/delete/', JournalDelete.as_view()),
]

expenses/models.py
from django.db import models
import pytz

# Create your models here.
# 支出紀錄
class Expense(models.Model):
    CATE_UNDEFINED      = 0
    CATE_EATING         = 1
    CATE_CLOTHING       = 2
    CATE_TRANSPORTATION = 3
    CATE_EDUCATION      = 4
    CATE_ENTERTAINMENT  = 5
    CATE_OTHER          = 99

    CATEGORY_CHOICES = (
      (CATE_UNDEFINED,      "未分類"),
      (CATE_EATING,         "飲食"),
      (CATE_CLOTHING,       "衣服"),
      (CATE_TRANSPORTATION, "交通"),
      (CATE_EDUCATION,      "教育"),
      (CATE_ENTERTAINMENT,  "娛樂"),
      (CATE_OTHER,          "其它"),
    )

    # 欄位定義
    item     = models.CharField('項目', max_length=30)
    category = models.IntegerField('支出類別', default=0, choices=CATEGORY_CHOICES)
    amount   = models.IntegerField('支出金額', default=0)
    time     = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{} {} : {} 元".format(
            self.time.astimezone(pytz.timezone('Asia/Taipei')).strftime('%Y-%m-%d %H:%M:%S'),
            self.item, 
            self.amount
        )

journal/models.py
from django.db import models

# Create your models here.
# 日誌
class Journal(models.Model):
    content = models.TextField("內容")
    created = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.content

expenses/views.py
from django.views.generic import *
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from .models import Expense

# Create your views here.
# 支出紀錄列表
class ExpenseList(LoginRequiredMixin, ListView):
    model = Expense
    ordering = ['-id']  # 反向排序
    paginate_by = 10    # 每頁顯示幾筆

# 新增支出紀錄
class ExpenseCreate(LoginRequiredMixin, CreateView):
    model = Expense
    fields = '__all__'  # 在表單上顯示*所有*欄位
    template_name = 'form.html'             # 指定使用 form.html 這個頁面範本

    def get_success_url(self):
        return reverse('expense_list')      # 新增成功返回支出紀錄列表頁面

# 修改支出紀錄
class ExpenseUpdate(LoginRequiredMixin, UpdateView):
    model = Expense
    fields = '__all__'
    template_name = 'form.html'

    def get_success_url(self):
        return reverse('expense_list')      # 修改成功返回支出紀錄列表頁面

# 刪除支出紀錄
class ExpenseDelete(LoginRequiredMixin, DeleteView):
    model = Expense
    template_name = 'confirm_delete.html'

    def get_success_url(self):
        return reverse('expense_list')      # 刪除成功返回支出紀錄列表頁面

journal/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from .models import Journal
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
# 日誌列表
class JournalList(LoginRequiredMixin, ListView):
    model = Journal
    ordering = ['-id']      # 依 id 欄位反向排序(新的在前面)
    paginate_by = 3         # 設定每頁最多顯示的資料筆數

# 新增日誌
class JournalCreate(LoginRequiredMixin, CreateView):
    model = Journal
    fields = ['content']            # 自動產生表單時僅顯示 content 欄位
    success_url = '/journal/'       # 操作成功後重新導向日誌列表頁面
    template_name = 'form.html'

# 修改日誌
class JournalUpdate(LoginRequiredMixin, UpdateView):
    model = Journal
    fields = ['content']            # 自動產生表單時僅顯示 content 欄位
    success_url = '/journal/'       # 操作成功後重新導向日誌列表頁面
    template_name = 'form.html'

# 刪除日誌
class JournalDelete(LoginRequiredMixin, DeleteView):
    model = Journal
    success_url = '/journal/'       # 操作成功後重新導向日誌列表頁面
    template_name = 'confirm_delete.html'

templates/base.html
<!DOCTYPE html>
<html lang="zh-hant">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>數位助理</title>
</head>
<body>
  <h1>數位助理</h1>
  <div>
    <a href="/journal/">日誌列表</a>
    <a href="/journal/create/">寫日誌</a>
    <a href="{% url 'expense_list' %}">支出紀錄列表</a>
    <a href="{% url 'expense_create' %}">新增支出紀錄</a>
    {% if user.is_authenticated %}
      {{ user.username }} <a href="{% url 'logout' %}">登出</a>
    {% else %}
      <a href="{% url 'login' %}">登入</a>
    {% endif %}
  </div>
  <div>{% block content %}{% endblock %}</div>
</body>
</html>

templates/confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<h2>刪除紀錄</h2>
<p>{{ object }}</p>
<p>確定要刪除這筆記錄嗎？</p>

<form action="" method="post">
  {% csrf_token %}
  <input type="submit" value="是的，我要刪除" />
</form>
{% endblock %}

templates/delete.html
{% extends 'base.html' %}

{% block content %}
<h2>刪除紀錄</h2>
<p>{{ object }}</p>
<p>確定要刪除這筆記錄嗎？</p>

<form action="" method="post">
  {% csrf_token %}
  <input type="submit" value="是的，我要刪除" />
</form>
{% endblock %}

templates/expenses/expense_list.html
{% extends "base.html" %}

{% block content %}
<h2>我的支出紀錄</h2>
<table>
  <tr>
    <th>時間</th>
    <th>項目</th>
    <th>類別</th>
    <th>金額</th>
    <th>功能</th>
  </tr>
  {% for expense in expense_list %}
  <tr>
    <td>({{ expense.time|date:"l" }}) {{ expense.time }}</td>
    <td><a href="{{ expense.id }}/update/">{{ expense.item }}</a></td>
    <td>{{ expense.get_category_display }}</td>
    <td>{{ expense.amount }}</td>
    <td><a href="{{ expense.id }}/delete/">刪除</a></td>
  </tr>
  {% endfor %}
</table>
{% include 'pagination.html' %}
{% endblock content %}

templates/form.html
{% extends 'base.html' %}

{% block content %}
<form action="" method="post">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="送出" />
</form>
{% endblock %}

templates/journal/journal_list.html
{% extends 'base.html' %}

{% block content %}
<h2>我的日誌</h2>
<table>
  <tr>
    <th>時間</th>
    <th>項目</th>
    <th>操作</th>
  </tr>
  {% for journal in journal_list %}
  <tr>
    <td>{{ journal.created|date:"l" }}{{ journal.created }}</td>
    <td><a href="{{ journal.id }}/update/">{{ journal.content }}</a></td>
    <td><a href="{{ journal.id }}/delete/">刪除</a></td>
  </tr>
  {% endfor %}
</table>
{% include 'pagination.html' %}
{% endblock %}

templates/pagination.html
{% if is_paginated %}
  <div>
  {% if page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}">上一頁</a>
  {% endif %}
  {% for page in paginator.page_range %}
    {% if page == page_obj.number %}
      <span>{{ page }}</span>
    {% else %}
      <a href="?page={{ page }}">{{ page }}</a>
    {% endif %}
  {% endfor %}
  {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">下一頁</a>
  {% endif %}
  </div>
{% endif %}